/*
    [CLUSTERING FACTOR] P.96
    - 데이터가 모여있는 정도
    - 높을수록 블록 I/O 감소, 속도증가
*/

-- 통계 수집하기
EXECUTE DBMS_STATS.GATHER_TABLE_STATS ('DEV', 'ORD_ITEM');
EXECUTE DBMS_STATS.GATHER_TABLE_STATS ('DEV', 'ORD_ITEM_RANDOM');


-- 오라클에서 다음과 같이 클러스터링 펙터 통계정보 조회 가능
-- 클러그터링 펙터는 인덱스를 통해 데이터를 읽으면서 블록이 바뀔때마다 1씩 증가
-- BLOCK 수에 가까울 수록 좋고 ROW 수에 가까울 수록 나쁨
SELECT
    T.TABLE_NAME
    , I.INDEX_NAME
    , T.BLOCKS
    , T.NUM_ROWS
    , I.CLUSTERING_FACTOR
FROM
    USER_TABLES T, USER_INDEXES I
WHERE
    I.TABLE_NAME = T.TABLE_NAME
    AND T.TABLE_NAME IN ('ORD_ITEM', 'ORD_ITEM_RANDOM');


-- 랜덤엑세스 횟수 실제로 비교해보기
EXPLAIN PLAN FOR
SELECT /*+ INDEX(OI ORD_ITEM_PK) */
    * FROM ORD_ITEM OI WHERE ROWNUM <=100

UNION ALL

SELECT /*+ INDEX(OIR ORD_ITEM_RANDOM_PK) */
    * FROM ORD_ITEM_RANDOM OIR WHERE ROWNUM <=100;

-- 확인
ALTER SYSTEM SET STATISTICS_LEVEL = TYPICAL;
ALTER SESSION SET "_ROWSOURCE_EXECUTION_STATISTICS"=TRUE;
SELECT * FROM TABLE ( DBMS_XPLAN.DISPLAY );
SELECT * FROM TABLE ( DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ADVANCED ALLSTATS LAST') );