/*
    [인덱스 스캔 방식] p.78
    1. INDEX UNIQUE SCAN
    2. INDEX RANGE SCAN
*/

-- (1) INDEX UNIQUE SCAN
-- 루트블록에서 시작해 테이블 블록에서 최종 1건 데이터 찾기
EXPLAIN PLAN FOR
    SELECT * FROM ITEM WHERE ITEM_ID = 11;

SELECT * FROM TABLE ( DBMS_XPLAN.DISPLAY );

-- (2) INDEX RANGE SCAN
-- 
EXPLAIN PLAN FOR
    SELECT * FROM UITEM WHERE ITEM_ID = 89;

SELECT * FROM TABLE ( DBMS_XPLAN.DISPLAY );