/*
    [INDEX COMBINE] P.89
    - 힌트 : INDEX_COMBINE(테이블 인덱스1 인덱스2)
    - 한 테이블에서 두개의 인덱스 사용 가능
    - 두개의 인덱스를 사용해 각각의 결과 집합으로 ROWID 생성 후 조건절에 따라 AND/OR 연산
*/

DROP INDEX ITEM_X03;
CREATE INDEX ITEM_X03 ON ITEM (ITEM_TYPE_CD);

-- 1
EXPLAIN PLAN FOR
    SELECT /*+ INDEX_COMBINE(ITEM ITEM_X01 ITEM_X03) */
        ITEM_TYPE_CD, ITEM_NM FROM ITEM WHERE ITEM_NM LIKE '%버거' AND ITEM_TYPE_CD < 100104;

-- 2
EXPLAIN PLAN FOR
    SELECT /*+ INDEX_COMBINE(ITEM ITEM_X01 ITEM_X03) */
        * FROM ITEM WHERE ITEM_TYPE_CD > 100102 OR ITEM_NM LIKE '%버거';

SELECT * FROM TABLE ( DBMS_XPLAN.DISPLAY );


