/*
    [실행계획 출력]
*/

EXPLAIN PLAN FOR
    SELECT * FROM ITEM;
SELECT * FROM TABLE ( DBMS_XPLAN.DISPLAY );

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ADVANCED ALLSTATS LAST'));

ALTER SYSTEM SET STATISTICS_LEVEL = ALL;
ALTER SESSION SET "_rowsource_execution_statistics" = TRUE;

ALTER SYSTEM SET STATISTICS_LEVEL = TYPICAL;
ALTER SESSION SET "_rowsource_execution_statistics" = TRUE;
