/*  [인덱스를 이용한 소트 대체]
    - 인덱스는 생성 컬럼을 기준으로 항상 정렬되어있음 => ORDER BY, GROUP BY 명령이 있을 때 인덱스를 이용해 소트 대체 가능.
*/

-- 1. SORT ORDER BY 연산 대체하기

-- 1.1 인덱스를 사용하지 않을 경우
DROP INDEX SHOP_X01;

EXPLAIN PLAN FOR
SELECT * FROM SHOP ORDER BY SHOP_NM;

-- 1.2 인덱스를 사용할 경우
CREATE INDEX SHOP_X01 ON SHOP(SHOP_NM);

EXPLAIN PLAN FOR
SELECT /*+ INDEX(SHOP SHOP_X01) */ SHOP_NM
FROM SHOP
ORDER BY SHOP_NM; -- 인덱스 생성 및 힌트를 넣어도 여전히 SORT ORDER BY 연산을 수행한다.

EXPLAIN PLAN FOR
SELECT SHOP_NM
FROM SHOP
WHERE SHOP_NM IS NOT NULL
ORDER BY SHOP_NM; -- SHOP_NM 컬럼에 NOT NULL 조건을 추가해주면 인덱스를 사용할 수 있게 된다.

-- 2. SORT GROUP BY 연산 대체하기

-- 인덱스 사용 안할 경우
DROP INDEX SHOP_X01;

EXPLAIN PLAN FOR
SELECT SHOP_NM
FROM SHOP
GROUP BY SHOP_NM; -- HASH GROUP BY 수행

-- 인덱스 사용 시
CREATE INDEX SHOP_X01 ON SHOP(SHOP_NM);

EXPLAIN PLAN FOR
SELECT SHOP_NM
FROM SHOP
WHERE SHOP_NM IS NOT NULL
GROUP BY SHOP_NM; -- SORT GROUP BY NOSORT (SORT 연산 생략됨)

-- 확인
SELECT * FROM TABLE ( DBMS_XPLAN.DISPLAY );

