/*  [소트 연산의 종류]
    1. ORDER BY : 실행계획에서는 SORT ORDER BY 연산으로 수행.
    2. GROUP BY : GROUP BY 연산과 ORDER BY 명령을 SQL문에 동시에 사용하면 SORT GROUP BY 연산으로 수행, 정렬 알고리즘을 사용해 GROUP BY 수행.
    3. 집합연산자 (DISTINCT, IN, UNION, MINUS, INTERSECT 등) : SORT UNIQUE 및 HASH UNIQUE 연산 발생.
    4. 윈도우 함수(WINDOW SORT) : Rank(), Dense_Rank(), Row_Number() 등.
    5. Sort Aggregate 연산 : 실행계획에서 SORT AGGREGATE 연산은 정렬하는것처럼 보이지만 실제론 정렬하지 않는다.
*/

-- 1. ORDER BY
EXPLAIN PLAN FOR
SELECT * FROM ITEM ORDER BY ITEM_ID;

-- 2. GROUP BY

-- 2.1 SORT GROUP BY
-- GROUP BY 와 ORDER BY 동시에 사용 시
EXPLAIN PLAN FOR
SELECT ITEM_ID, COUNT(ITEM_ID) FROM UITEM GROUP BY ITEM_ID ORDER BY ITEM_ID;

-- 2.2 HASH GROUP BY
-- GROUP BY 만 수행할땐 대부분 해시 알고리즘 사용.
EXPLAIN PLAN FOR
SELECT COUNT(*) FROM SHOP GROUP BY SHOP_NM;

-- 3. 집합연산자 (DISTINCT, IN, UNION, MINUS, INTERSECT 등)

-- 3.1 SORT UNIQUE
-- SORT(정렬) 후 UNIQUE(중복제거)
EXPLAIN PLAN FOR
SELECT * FROM UITEM WHERE ITEM_ID IN (60, 70, 80, 90);

SELECT * FROM TABLE ( DBMS_XPLAN.DISPLAY );
SELECT * FROM TABLE ( DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ADVANCED ALLSTATS LAST') );


